#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues
# remove the default Nginx configurations file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 for all active IPv4 IPs
in -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
