#!/usr/bin/env bash
# Installing new server to serve content

in -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminatesz the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
